version:  "3.7"

services:
  sep_app:
    container_name: sep_app_test
    image: yangyipoh/sep_app
    ports:
      - "8501:8501"
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
